In [9]:
import numpy as np
import pandas as pd
from scipy import stats

In [4]:
print("h")

h


In [5]:
print("h")

h


In [11]:
arr1=np.random.randint(10,20,size=15)
arr1

array([14, 16, 18, 10, 16, 11, 17, 17, 15, 11, 13, 19, 18, 14, 18])

In [12]:
arr2=np.random.randint(10,20,size=15)
arr2

array([19, 10, 13, 15, 18, 14, 16, 12, 18, 10, 14, 17, 14, 12, 18])

In [13]:
stats.zscore(arr1)

array([-0.40801306,  0.31200998,  1.03203303, -1.84805914,  0.31200998,
       -1.48804762,  0.67202151,  0.67202151, -0.04800154, -1.48804762,
       -0.76802458,  1.39204455,  1.03203303, -0.40801306,  1.03203303])

In [14]:
stats.zscore(arr2)

array([ 1.5236235 , -1.64082531, -0.58600904,  0.11720181,  1.17201808,
       -0.23440362,  0.46880723, -0.93761446,  1.17201808, -1.64082531,
       -0.23440362,  0.82041265, -0.23440362, -0.93761446,  1.17201808])

In [16]:
z_score=np.abs(stats.zscore(arr1))
z_score

array([0.40801306, 0.31200998, 1.03203303, 1.84805914, 0.31200998,
       1.48804762, 0.67202151, 0.67202151, 0.04800154, 1.48804762,
       0.76802458, 1.39204455, 1.03203303, 0.40801306, 1.03203303])

In [17]:
arr2=[19, 10, 13, 15, 18, 14,113, 16, 12, 18, 10, 14, 17, 14, 12, 18]
arr2

[19, 10, 13, 15, 18, 14, 113, 16, 12, 18, 10, 14, 17, 14, 12, 18]

In [18]:
z_score2=np.abs(stats.zscore(arr2))
z_score2

array([0.07564225, 0.45124515, 0.32604419, 0.24257687, 0.11737591,
       0.28431053, 3.84732139, 0.20084322, 0.36777784, 0.11737591,
       0.45124515, 0.28431053, 0.15910956, 0.28431053, 0.36777784,
       0.11737591])

In [19]:
thresh=3
out_index=np.where(z_score2>thresh)

(array([6], dtype=int64),)

In [20]:
arr2[out_index]

NameError: name 'out_index' is not defined