In [ ]:
import pandas as pd
import numpy as np

from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, multilabel_confusion_matrix

In [ ]:
df = pd.read_csv('Iris.csv')

In [ ]:
# df

In [ ]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [ ]:
df['Species'].replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2},inplace = True)

In [ ]:
df.head(3)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0

In [ ]:
x = df.drop(['Id','Species'],axis = 1)
y = df['Species']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state=10, stratify=y)

In [ ]:
ab_model = AdaBoostClassifier(random_state=1)
ab_model.fit(x_train, y_train)

AdaBoostClassifier(random_state=1)

# Evaluation

In [ ]:
# Evaluation on Test Data

y_pred = ab_model.predict(x_test)

test_accuracy = accuracy_score(y_test, y_pred)
print('Accuracy of model is :',test_accuracy)

clf_report = classification_report(y_test, y_pred)
print("Classification Report :\n",clf_report)

Accuracy of model is : 1.0
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
# Evaluation on Train Data

y_pred_train = ab_model.predict(x_train)

train_accuracy = accuracy_score(y_train, y_pred_train)
print('Accuracy of model is :',train_accuracy)

clf_report = classification_report(y_train, y_pred_train)
print("Classification Report :\n",clf_report)

print(confusion_matrix(y_train, y_pred_train))

multilabel_confusion_matrix(y_train, y_pred_train)

Accuracy of model is : 0.95
Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.90      0.95      0.93        40
           2       0.95      0.90      0.92        40

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120

[[40  0  0]
 [ 0 38  2]
 [ 0  4 36]]


array([[[80,  0],
        [ 0, 40]],

       [[76,  4],
        [ 2, 38]],

       [[78,  2],
        [ 4, 36]]], dtype=int64)